[book]
title = "everystep"
authors = ["weijiew"]
language = "zh-CN"
src = "src"


[output.html]
additional-css = ["theme/style.css"]
# additional-js = ["theme/custom.js"]
git-repository-url = "https://github.com/weijiew/everystep"
edit-url-template = "https://github.com/weijiew/everystep/edit/main/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = true
level = 0

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
