[book]
title = "everystep"
authors = ["rainjw"]
language = "zh-CN"
src = "src"


[output.html]
additional-css = ["theme/style.css"]
additional-js = ["theme/custom.js"]
git-repository-url = "https://github.com/rainjw/everystep"
edit-url-template = "https://github.com/rainjw/everystep/edit/main/{path}"

[output.html.playground]
editable = true
copy-js = true
# line-numbers = true

[output.html.fold]
enable = true
level = 0
